app = 'YOUR_APP_NAME'
primary_region = 'iad'

[build]
  image = 'ghcr.io/lobby-ws/gamedev:main'

[env]
  ASSETS = 'local'
  ASSETS_BASE_URL = 'https://YOUR_APP_NAME.fly.dev/assets'
  ASSETS_S3_URI = ''
  CLEAN = 'true'
  DB_SCHEMA = '.'
  DB_URI = 'local'
  PORT = '3000'
  PUBLIC_API_URL = 'https://YOUR_APP_NAME.fly.dev/api'
  PUBLIC_DEV_SERVER = 'false'
  PUBLIC_MAX_UPLOAD_SIZE = '12'
  PUBLIC_PLAYER_COLLISION = 'false'
  PUBLIC_WS_URL = 'wss://YOUR_APP_NAME.fly.dev/ws'
  REGISTRY_ENABLED = 'true'
  REGISTRY_JOIN_URL = ''
  REGISTRY_URL = ''
  SAVE_INTERVAL = '60'
  WORLD = 'world'
  WORLD_URL = 'https://YOUR_APP_NAME.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
